### PR TITLE
feat: use node20 and upgrade ncc

### PR DESCRIPTION
**Pull request by chenrui333**
This is consistent with all the recent github action updates. (mostly in actions repos, like actions/checkout, actions/setup-node, etc.)

-------

Node12 was deleted from runner. Node20 was added to Actions Runner on v2.308.0.
Node16 has en end of life on 11 Sep 2023.

This PR updates the default runtime to node20, rather then node16

relates to https://github.com/actions/runner/pull/2732

### CODE REVIEW

**Comment by timheuer** [comment]
Thanks @chenrui333 -- I'll take a look and hopefully merge this today.

**Comment by timheuer** [comment]
@all-contributors please add @chenrui333 for Code

**Comment by chenrui333** [comment]
@timheuer you would also need a major version release per this change. (forgot to specify in the PR desc), and thanks for the merge! 🎉

**Comment by timheuer** [comment]
> @timheuer you would also need a major version release per this change. (forgot to specify in the PR desc), and thanks for the merge! 🎉

What do you mean here? I've updated the v1, v1.2 tags to this commit.

**Comment by chenrui333** [comment]
> > @timheuer you would also need a major version release per this change. (forgot to specify in the PR desc), and thanks for the merge! 🎉
> 
> What do you mean here? I've updated the v1, v1.2 tags to this commit.

yeah, should be a major version bump in terms of release semantics (also aligns with the github setup-* actions)

**Comment by timheuer** [comment]
Got it.  In this case, I've not treated these updates as such and ensured minor/revision are updated and tags as well.  There isn't any major functionality change here (none in fact) and it is more clearing the warnings that would happen.

**Comment by chenrui333** [comment]
> Got it. In this case, I've not treated these updates as such and ensured minor/revision are updated and tags as well. There isn't any major functionality change here (none in fact) and it is more clearing the warnings that would happen.

this is mostly tied with how we interpret the release semantics, in terms of the action itself, yeah, I agree, there is no function change, but in terms of dependant runtime, there is a big reference (because the nature of the action runtime tied with the runner I do feel like it would be nice to make it a major release) 

Sometimes people are actually using `appVersion-runtimeVersion` (like jdk-scala), which I feel a bit too much :)

**Pull request merged**
